--------------------------------------------------------
--  파일이 생성됨 - 화요일-2월-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "GOURMET"."STORE" 
   (	"STORENUM" NUMBER, 
	"STNAME" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"STTEL" NUMBER, 
	"RATE" NUMBER, 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"INFO" VARCHAR2(50 BYTE), 
	"IMAGE" VARCHAR2(500 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GOURMET.STORE
SET DEFINE OFF;
Insert into GOURMET.STORE (STORENUM,STNAME,ADDRESS,STTEL,RATE,CATEGORY,INFO,IMAGE,REGIDATE) values (13,'코딩삼겹살','뉴런',10101010,1,'Korean','코딩하다 불난 컴퓨터로 굽는 고깃집','C4.jpg',to_date('24/02/13','RR/MM/DD'));
Insert into GOURMET.STORE (STORENUM,STNAME,ADDRESS,STTEL,RATE,CATEGORY,INFO,IMAGE,REGIDATE) values (15,'쭈구렁피자','꼬부랑길',88,1,'Italian','우준이가 허리펴고싶어 만든 피잣집','G4.jpg',to_date('24/02/13','RR/MM/DD'));
Insert into GOURMET.STORE (STORENUM,STNAME,ADDRESS,STTEL,RATE,CATEGORY,INFO,IMAGE,REGIDATE) values (10,'우준반점','노예집',1012345678,5,'Korean','bbb','wjcuisin.jpg',to_date('24/02/13','RR/MM/DD'));
Insert into GOURMET.STORE (STORENUM,STNAME,ADDRESS,STTEL,RATE,CATEGORY,INFO,IMAGE,REGIDATE) values (11,'보석바','노예집1',231564231,5,'Italian','ㅠㅠㅠㅠㅠ','B1.jpg',to_date('24/02/13','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007088
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOURMET"."SYS_C007088" ON "GOURMET"."STORE" ("STORENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "GOURMET"."STORE" ADD PRIMARY KEY ("STORENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOURMET"."STORE" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("INFO" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("RATE" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("STTEL" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "GOURMET"."STORE" MODIFY ("STNAME" NOT NULL ENABLE);
